name: e-wallet
services:
  db:
    container_name: e-wallet-db
    image: postgres:14.6-alpine
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
    ports:
      - "5432:5432"
    volumes:
      - ewallet_postgres_data:/var/lib/postgresql/data
    networks:
      - ewallet_network
    expose:
      - 5432
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  frontend:
    container_name: e-wallet-frontend
    image: rida999/e-wallet-frontend:latest
    restart: always
    env_file: ./.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ewallet_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  backend:
    container_name: e-wallet-backend
    image: rida999/e-wallet-backend:latest
    env_file: ./.env
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${db_name}
      SPRING_DATASOURCE_USERNAME: ${db_username}
      SPRING_DATASOURCE_PASSWORD: ${db_password}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ewallet_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

volumes:
  ewallet_postgres_data:
    driver: local

networks:
  ewallet_network:
    driver: bridge
